- name: Update packages on each servers
  hosts:
    - grafana-server
    - prometheus-server
    - loki-server
    - goapp-server
    - nginx-server
    - tempo-server
  become: yes
  roles:
    - linux
