- name: Set hostname
  hostname:
    name: "{{ hostname }}"
    
- name: Install prerequisites
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
      - apt-transport-https
      - software-properties-common
      - wget

- name: Add Grafana GPG key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
  notify:
    - Update apt cache

- name: Install Grafana
  apt:
    name: grafana
    state: present

- name: Reload systemd
  ansible.builtin.command:
    cmd: "systemctl daemon-reload"

- name: Start Grafana service
  ansible.builtin.systemd:
    name: grafana-server
    state: started

- name: Enable Grafana service
  ansible.builtin.systemd:
    name: grafana-server
    enabled: yes